#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Oct 22, 2018 05:04:36 PM AST  platform: Linux

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global r1
    r1 = DoubleVar()
    global r3
    r3 = DoubleVar()
    global s_min
    s_min = DoubleVar()
    global s_max
    s_max = DoubleVar()
    global pv_min
    pv_min = DoubleVar()
    global pv_max
    pv_max = DoubleVar()
    global sp_min
    sp_min = DoubleVar()
    global sp_max
    sp_max = DoubleVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Span_and_Kp
    Span_and_Kp.vp_start_gui()


